# https://github.com/actions/stale
name: autoCloseIssue

on:
  schedule:
    # 每5天北京时间9点
    - cron: '30 1 1/5 * *'
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: '由于该问题长期没有更新，将于5天后自动关闭。如有需要可重新打开。'
          days-before-stale: 30
          days-before-close: 5
          operations-per-run: 100