[package]
authors = ["ihciah <ihciah@gmail.com>"]
edition = "2021"
license = "MIT/Apache-2.0"
name = "shadow-tls"
version = "0.1.0"

[dependencies]
monoio = {version = "0.0.8"}
monoio-rustls = {version = "0.0.6"}

anyhow = "1"
clap = {version = "3", features = ["derive"]}
pin-project-lite = "0.2"
rustls = {version = "0.20", default-features = false}
tracing = "0.1"
tracing-subscriber = "0.3"
webpki-roots = "0.22"

[features]
default = ["zero-copy"]

# Relay data with splice syscall for linux.
zero-copy = ["monoio/splice"]

[profile.release]
lto = true
opt-level = 3
