[package]
name = "clash-verge"
version = "0.1.0"
description = "clash verge"
authors = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
default-run = "clash-verge"
edition = { workspace = true }
build = "build.rs"

[build-dependencies]
tauri-build = { version = "1", features = [] }
serde = "1"
simd-json = "0.13"

[dependencies]
warp = "0.3"
which = "6"
anyhow = "1.0"
dirs = "5.0.1"
open = "5.0.1"
log = "0.4.20"
ctrlc = "3.4.2"
dunce = "1.0.4"
nanoid = "0.4.0"
chrono = "0.4.31"
sysinfo = "0.30"
sysproxy = { path = "../sysproxy-rs", version = "0.3" }
rquickjs = "0.5.0"
serde_json = "1.0"
serde_yaml = "0.9"
auto-launch = "0.5"
once_cell = "1.19.0"
port_scanner = "0.1.5"
delay_timer = "0.11.5"
parking_lot = { version = "0.12.1" }
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
reqwest = { version = "0.11", features = ["json", "rustls-tls"] }
tauri = { version = "1.5.4", features = [
  "updater",
  "os-all",
  "global-shortcut-all",
  "notification-all",
  "process-all",
  "shell-all",
  "system-tray",
  "window-all",
] }
window-vibrancy = { version = "0.5.0" }
window-shadows = { version = "0.2.2" }
wry = { version = "0.24.6" }
semver = "1.0"
zip = "0.6.6"
zip-extensions = "0.6.2"
gunzip = { version = "0.1.0", git = "https://github.com/TechHara/gunzip.git" }
tempfile = "3.9.0"
glob = "0.3.1"
async-trait = "0.1.77"
dyn-clone = "1.0.16"
rs-snowflake = "0.6"
rocksdb = "0.22"
thiserror = { workspace = true }
simd-json = "0.13.8"
runas = "1.2.0"
backon = "0.4.1"
rust-i18n = "3"
adler = "1.0.2"
rfd = "0.10" # should bump to v0.14 when clarify why the rfd v0.10 from tauri breaks build
indexmap = { version = "2.2.3", features = ["serde"] }
tracing = { workspace = true }
tracing-attributes = "0.1"
tracing-futures = "0.2"
tracing-subscriber = { version = "0.3", features = [
  "env-filter",
  "json",
  "parking_lot",
] }
tracing-error = "0.2"
tracing-log = { version = "0.2" }
tracing-appender = { version = "0.2", features = ["parking_lot"] }
base64 = "0.22"
single-instance = "0.3.3"
tauri-plugin-deep-link = { path = "../tauri-plugin-deep-link", version = "0.1.2" }
uuid = "1.7.0"
image = "0.24.9"
fast_image_resize = "3.0.4"
display-info = "0.5.0" # should be removed after upgrading to tauri v2
dashmap = "5.5.3"

[target.'cfg(windows)'.dependencies]
deelevate = "0.2.0"
winreg = { version = "0.52", features = ["transactions"] }
windows-sys = { version = "0.52", features = [
  "Win32_System_LibraryLoader",
  "Win32_System_SystemInformation",
] }

[target.'cfg(windows)'.dependencies.tauri]
version = "1.5.4"
features = [
  "global-shortcut-all",
  "icon-png",
  "process-all",
  "dialog-all",
  "shell-all",
  "system-tray",
  "updater",
  "window-all",
]

[target.'cfg(linux)'.dependencies.tauri]
version = "1.5.4"
features = [
  "global-shortcut-all",
  "process-all",
  "dialog-all",
  "shell-all",
  "system-tray",
  "updater",
  "window-all",
  "native-tls-vendored",
  "reqwest-native-tls-vendored",
]

[features]
default = ["custom-protocol", "default-meta"]
custom-protocol = ["tauri/custom-protocol"]
verge-dev = []
default-meta = []
nightly = []
deadlock-detection = ["parking_lot/deadlock_detection"]
