name: 'external connection test'
on: [workflow_dispatch]
jobs:
  run-test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Build test binaries
        run: make test-binary
      - name: Run packet drop test
        run: sudo ./test/deploy/externalconnect/test.sh
