name: 'integration test'
on: [workflow_dispatch]
jobs:
  run-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.7
      - name: Run integration test
        run: make run-container-test
