name: 'packet drop test'
on: [workflow_dispatch]
jobs:
  run-test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21.7
      - name: Build test binaries
        run: make test-binary
      - name: Run packet drop test
        run: sudo ./test/deploy/packetdrop/test.sh
