name: gost
base: core20
version: '2.11.3'
summary: A simple security tunnel written in golang
description: |
  Project: https://github.com/ginuerzh/gost
  Wiki: https://v2.gost.run
icon: gost.png
website: https://v2.gost.run
license: MIT


confinement: strict
grade: stable

parts:
  gost:
    plugin: go
    go-channel: latest/stable
    source: https://github.com/ginuerzh/gost
    source-subdir: cmd/gost
    source-type: git
    source-tag: v2.11.3
    build-packages:
    - gcc

apps:
  gost:
    command: bin/gost
    plugs: 
    - home
    - network
    - network-bind

