name: shadowsocks-rust
adopt-info: shadowsocks-rust
summary: Rust port of Shadowsocks
description: |
  Shadowsocks Client & Server, written in Rust.
base: core22
grade: stable
confinement: strict
architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf
  # - build-on: ppc64el
  # - build-on: s390x
  - build-on: riscv64
license: MIT
source-code: https://github.com/shadowsocks/shadowsocks-rust

apps:
  sslocal:
    command: bin/sslocal
    plugs: [network, network-bind, network-control, home, system-bin-files]
    aliases: [sslocal]

  sslocal-daemon:
    command: bin/sslocal
    daemon: simple
    install-mode: disable
    plugs: [network, network-bind, network-control, home, system-bin-files]

  ssserver:
    command: bin/ssserver
    plugs: [network, network-bind, home, system-bin-files]
    aliases: [ssserver]

  ssserver-daemon:
    command: bin/ssserver
    daemon: simple
    install-mode: disable
    plugs: [network, network-bind, home, system-bin-files]

  ssurl:
    command: bin/ssurl
    aliases: [ssurl]

  ssmanager:
    command: bin/ssmanager
    plugs: [network, network-bind, home, system-bin-files]
    aliases: [ssmanager]

passthrough:
  layout:
    /etc/shadowsocks-rust:
      bind: $SNAP_COMMON/etc/shadowsocks-rust

plugs:
  system-bin-files:
    interface: system-files
    read:
      - /bin
      - /usr/bin
      - /usr/local/bin

parts:
  shadowsocks-rust:
    plugin: rust
    source: https://github.com/shadowsocks/shadowsocks-rust.git
    rust-channel: stable
    rust-features: [local-tun, local-redir]
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version `git describe --tags --long | sed 's/\([^-]*-g\)/r\1/;s/-/./g'`
