[build]
pre-build = [
    # https://aws.github.io/aws-lc-rs/requirements/linux.html
    "apt-get update",
    "apt-get install --assume-yes llvm-5.0-dev libclang-5.0-dev clang-5.0",
    "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal --default-toolchain stable",
    ". $HOME/.cargo/env",
    "cargo install --force --locked bindgen-cli && mv $HOME/.cargo/bin/bindgen /usr/bin",
    "rustup self uninstall -y",
]

[build.env]
passthrough = ["RUSTFLAGS"]

[target.x86_64-pc-windows-gnu]
pre-build = [
    # Install NASM for rustls, which deps on aws-lc-rs by default, and it needs NASM
    "apt-get update",
    "apt-get install --assume-yes llvm-5.0-dev libclang-5.0-dev clang-5.0 nasm",
    "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal --default-toolchain stable",
    ". $HOME/.cargo/env",
    "cargo install --force --locked bindgen-cli && mv $HOME/.cargo/bin/bindgen /usr/bin",
    "rustup self uninstall -y",
]

[target.aarch64-unknown-linux-gnu]
pre-build = []

[target.aarch64-unknown-linux-musl]
pre-build = []

[target.x86_64-unknown-linux-gnu]
pre-build = []

[target.x86_64-unknown-linux-musl]
pre-build = []

[target.i686-unknown-linux-gnu]
pre-build = []

[target.aarch64-apple-darwin]
pre-build = []

[target.x86_64-apple-darwin]
pre-build = []
